theme: jekyll-theme-architect
show_downloads: false
title: Chippewa Software
description: microapps - extending the microservice idea to microfrontend development
github:
  is_project_page: true
  repository_url: https://github.com/ChipSoftTech/chipsofttech.github.io
google_analytics: UA-XXXXX84095563-2
exclude:
  - 2-composition-universal
  - 3-data-fetching
  - node_modules
